*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YMTLV_DEFECT....................................*
FORM GET_DATA_YMTLV_DEFECT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YMTLT_DEFECT WHERE
(VIM_WHERETAB) .
    CLEAR YMTLV_DEFECT .
YMTLV_DEFECT-MANDT =
YMTLT_DEFECT-MANDT .
YMTLV_DEFECT-DEFECT_NR =
YMTLT_DEFECT-DEFECT_NR .
YMTLV_DEFECT-CREDAT =
YMTLT_DEFECT-CREDAT .
YMTLV_DEFECT-CRETIM =
YMTLT_DEFECT-CRETIM .
YMTLV_DEFECT-ERNAM =
YMTLT_DEFECT-ERNAM .
YMTLV_DEFECT-DEFCAT =
YMTLT_DEFECT-DEFCAT .
YMTLV_DEFECT-LGNUM =
YMTLT_DEFECT-LGNUM .
YMTLV_DEFECT-LGTYP =
YMTLT_DEFECT-LGTYP .
YMTLV_DEFECT-LGPLA =
YMTLT_DEFECT-LGPLA .
YMTLV_DEFECT-MATNR =
YMTLT_DEFECT-MATNR .
YMTLV_DEFECT-STATUS =
YMTLT_DEFECT-STATUS .
YMTLV_DEFECT-NOTES =
YMTLT_DEFECT-NOTES .
YMTLV_DEFECT-CLOSEDBY =
YMTLT_DEFECT-CLOSEDBY .
YMTLV_DEFECT-EMAIL_NEW =
YMTLT_DEFECT-EMAIL_NEW .
YMTLV_DEFECT-EMAIL_OPEN =
YMTLT_DEFECT-EMAIL_OPEN .
YMTLV_DEFECT-EMAIL_CLOSED =
YMTLT_DEFECT-EMAIL_CLOSED .
YMTLV_DEFECT-CLOSED_DATE =
YMTLT_DEFECT-CLOSED_DATE .
YMTLV_DEFECT-CLOSED_TIME =
YMTLT_DEFECT-CLOSED_TIME .
<VIM_TOTAL_STRUC> = YMTLV_DEFECT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YMTLV_DEFECT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YMTLV_DEFECT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YMTLV_DEFECT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YMTLT_DEFECT WHERE
  DEFECT_NR = YMTLV_DEFECT-DEFECT_NR .
    IF SY-SUBRC = 0.
    DELETE YMTLT_DEFECT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YMTLT_DEFECT WHERE
  DEFECT_NR = YMTLV_DEFECT-DEFECT_NR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YMTLT_DEFECT.
    ENDIF.
YMTLT_DEFECT-MANDT =
YMTLV_DEFECT-MANDT .
YMTLT_DEFECT-DEFECT_NR =
YMTLV_DEFECT-DEFECT_NR .
YMTLT_DEFECT-CREDAT =
YMTLV_DEFECT-CREDAT .
YMTLT_DEFECT-CRETIM =
YMTLV_DEFECT-CRETIM .
YMTLT_DEFECT-ERNAM =
YMTLV_DEFECT-ERNAM .
YMTLT_DEFECT-DEFCAT =
YMTLV_DEFECT-DEFCAT .
YMTLT_DEFECT-LGNUM =
YMTLV_DEFECT-LGNUM .
YMTLT_DEFECT-LGTYP =
YMTLV_DEFECT-LGTYP .
YMTLT_DEFECT-LGPLA =
YMTLV_DEFECT-LGPLA .
YMTLT_DEFECT-MATNR =
YMTLV_DEFECT-MATNR .
YMTLT_DEFECT-STATUS =
YMTLV_DEFECT-STATUS .
YMTLT_DEFECT-NOTES =
YMTLV_DEFECT-NOTES .
YMTLT_DEFECT-CLOSEDBY =
YMTLV_DEFECT-CLOSEDBY .
YMTLT_DEFECT-EMAIL_NEW =
YMTLV_DEFECT-EMAIL_NEW .
YMTLT_DEFECT-EMAIL_OPEN =
YMTLV_DEFECT-EMAIL_OPEN .
YMTLT_DEFECT-EMAIL_CLOSED =
YMTLV_DEFECT-EMAIL_CLOSED .
YMTLT_DEFECT-CLOSED_DATE =
YMTLV_DEFECT-CLOSED_DATE .
YMTLT_DEFECT-CLOSED_TIME =
YMTLV_DEFECT-CLOSED_TIME .
    IF SY-SUBRC = 0.
    UPDATE YMTLT_DEFECT .
    ELSE.
    INSERT YMTLT_DEFECT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YMTLV_DEFECT-UPD_FLAG,
STATUS_YMTLV_DEFECT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YMTLV_DEFECT.
  SELECT SINGLE * FROM YMTLT_DEFECT WHERE
DEFECT_NR = YMTLV_DEFECT-DEFECT_NR .
YMTLV_DEFECT-MANDT =
YMTLT_DEFECT-MANDT .
YMTLV_DEFECT-DEFECT_NR =
YMTLT_DEFECT-DEFECT_NR .
YMTLV_DEFECT-CREDAT =
YMTLT_DEFECT-CREDAT .
YMTLV_DEFECT-CRETIM =
YMTLT_DEFECT-CRETIM .
YMTLV_DEFECT-ERNAM =
YMTLT_DEFECT-ERNAM .
YMTLV_DEFECT-DEFCAT =
YMTLT_DEFECT-DEFCAT .
YMTLV_DEFECT-LGNUM =
YMTLT_DEFECT-LGNUM .
YMTLV_DEFECT-LGTYP =
YMTLT_DEFECT-LGTYP .
YMTLV_DEFECT-LGPLA =
YMTLT_DEFECT-LGPLA .
YMTLV_DEFECT-MATNR =
YMTLT_DEFECT-MATNR .
YMTLV_DEFECT-STATUS =
YMTLT_DEFECT-STATUS .
YMTLV_DEFECT-NOTES =
YMTLT_DEFECT-NOTES .
YMTLV_DEFECT-CLOSEDBY =
YMTLT_DEFECT-CLOSEDBY .
YMTLV_DEFECT-EMAIL_NEW =
YMTLT_DEFECT-EMAIL_NEW .
YMTLV_DEFECT-EMAIL_OPEN =
YMTLT_DEFECT-EMAIL_OPEN .
YMTLV_DEFECT-EMAIL_CLOSED =
YMTLT_DEFECT-EMAIL_CLOSED .
YMTLV_DEFECT-CLOSED_DATE =
YMTLT_DEFECT-CLOSED_DATE .
YMTLV_DEFECT-CLOSED_TIME =
YMTLT_DEFECT-CLOSED_TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YMTLV_DEFECT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YMTLV_DEFECT-DEFECT_NR TO
YMTLT_DEFECT-DEFECT_NR .
MOVE YMTLV_DEFECT-MANDT TO
YMTLT_DEFECT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YMTLT_DEFECT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YMTLT_DEFECT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YMTLT_DEFECT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
