*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: YMTLV_EMAIL_REC.................................*
FORM GET_DATA_YMTLV_EMAIL_REC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM YMTLT_EMAIL_REC WHERE
(VIM_WHERETAB) .
    CLEAR YMTLV_EMAIL_REC .
YMTLV_EMAIL_REC-MANDT =
YMTLT_EMAIL_REC-MANDT .
YMTLV_EMAIL_REC-EMAIL_LIST_ID =
YMTLT_EMAIL_REC-EMAIL_LIST_ID .
YMTLV_EMAIL_REC-SMTP_ADDR =
YMTLT_EMAIL_REC-SMTP_ADDR .
<VIM_TOTAL_STRUC> = YMTLV_EMAIL_REC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_YMTLV_EMAIL_REC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO YMTLV_EMAIL_REC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_YMTLV_EMAIL_REC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM YMTLT_EMAIL_REC WHERE
  EMAIL_LIST_ID = YMTLV_EMAIL_REC-EMAIL_LIST_ID AND
  SMTP_ADDR = YMTLV_EMAIL_REC-SMTP_ADDR .
    IF SY-SUBRC = 0.
    DELETE YMTLT_EMAIL_REC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM YMTLT_EMAIL_REC WHERE
  EMAIL_LIST_ID = YMTLV_EMAIL_REC-EMAIL_LIST_ID AND
  SMTP_ADDR = YMTLV_EMAIL_REC-SMTP_ADDR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR YMTLT_EMAIL_REC.
    ENDIF.
YMTLT_EMAIL_REC-MANDT =
YMTLV_EMAIL_REC-MANDT .
YMTLT_EMAIL_REC-EMAIL_LIST_ID =
YMTLV_EMAIL_REC-EMAIL_LIST_ID .
YMTLT_EMAIL_REC-SMTP_ADDR =
YMTLV_EMAIL_REC-SMTP_ADDR .
    IF SY-SUBRC = 0.
    UPDATE YMTLT_EMAIL_REC .
    ELSE.
    INSERT YMTLT_EMAIL_REC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_YMTLV_EMAIL_REC-UPD_FLAG,
STATUS_YMTLV_EMAIL_REC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_YMTLV_EMAIL_REC.
  SELECT SINGLE * FROM YMTLT_EMAIL_REC WHERE
EMAIL_LIST_ID = YMTLV_EMAIL_REC-EMAIL_LIST_ID AND
SMTP_ADDR = YMTLV_EMAIL_REC-SMTP_ADDR .
YMTLV_EMAIL_REC-MANDT =
YMTLT_EMAIL_REC-MANDT .
YMTLV_EMAIL_REC-EMAIL_LIST_ID =
YMTLT_EMAIL_REC-EMAIL_LIST_ID .
YMTLV_EMAIL_REC-SMTP_ADDR =
YMTLT_EMAIL_REC-SMTP_ADDR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_YMTLV_EMAIL_REC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE YMTLV_EMAIL_REC-EMAIL_LIST_ID TO
YMTLT_EMAIL_REC-EMAIL_LIST_ID .
MOVE YMTLV_EMAIL_REC-SMTP_ADDR TO
YMTLT_EMAIL_REC-SMTP_ADDR .
MOVE YMTLV_EMAIL_REC-MANDT TO
YMTLT_EMAIL_REC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'YMTLT_EMAIL_REC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN YMTLT_EMAIL_REC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'YMTLT_EMAIL_REC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
