FUNCTION Z_MSB_YSA_YMTL_DEF_002_PAI.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_APPL) TYPE  /MOBISYS/MSB_APPL OPTIONAL
*"     VALUE(I_DEVICEID) TYPE  /MOBISYS/MSB_DEVICEID OPTIONAL
*"     VALUE(I_EVENT) TYPE  /MOBISYS/MSB_CEVENT OPTIONAL
*"     VALUE(I_EVENTTYPE) TYPE  /MOBISYS/MSB_CEVENTTYPE OPTIONAL
*"     REFERENCE(I_HELPER) TYPE REF TO  /MOBISYS/CL_MSB_RTS OPTIONAL
*"     VALUE(I_MASK) TYPE  /MOBISYS/MSB_MASKID OPTIONAL
*"     VALUE(I_SESSION) TYPE  /MOBISYS/MSB_SESSION OPTIONAL
*"     VALUE(I_TCODE) TYPE  /MOBISYS/MSB_TCODE OPTIONAL
*"     VALUE(I_USER) TYPE  SYST-UNAME OPTIONAL
*"  EXPORTING
*"     VALUE(E_APPL) TYPE  /MOBISYS/MSB_APPL
*"     VALUE(E_MASK) TYPE  /MOBISYS/MSB_MASKID
*"     VALUE(E_MSGNO) TYPE  MSGNO
*"     VALUE(E_MSGTXT) TYPE  MSGTX
*"     VALUE(E_MSGTYP) TYPE  MSGTY
*"     VALUE(E_TCODE) TYPE  /MOBISYS/MSB_TCODE
*"     VALUE(E_USER) TYPE  /MOBISYS/MSB_UNAME
*"  TABLES
*"      VALUES STRUCTURE  /MOBISYS/MSB_STR_VALUE_IN OPTIONAL
*"  CHANGING
*"     REFERENCE(C_APPDATA) TYPE  /MOBISYS/MSB_APPDATA OPTIONAL
*"----------------------------------------------------------------------
**** PAI- generated by MSB 28.11.2022 ***
**** DO NOT CHANGE / CHANGES WILL BE OVERWRITTEN ***
*
  INCLUDE z_msb_ysa_ymtl_def_pai_entry .



* DATA EDT_LAGP_LGPLA TYPE LGPLA *.
* DATA EDT_MARA_MATNR TYPE MATNR *.
* DATA EDT_T301_LGTYP TYPE LGTYP *.
* DATA RBT_DAMGD_LABEL TYPE CHAR1 *.
* DATA RBT_DAMGD_RACK TYPE CHAR1 *.
* DATA RBT_INV_DISC TYPE CHAR1 *.


* >>> Begin of customer own coding >>>
*----------------------------------------------------------------------*
* Author: Marton Papp
* Date:   2022.02.22.
* CR/IN: CHG0083294 - HES project
*----------------------------------------------------------------------*
* Short description:
* Non-material defect creation
*----------------------------------------------------------------------*
* Changes
* Index Name         Date        Short description
*----------------------------------------------------------------------*

  DATA: lo_defect_category TYPE REF TO ymtle10358i_defect_category,
        lo_defect_dao      TYPE REF TO ymtle10358i_defect_dao.
  DO 1 TIMES.           "Generated Exit Include should be reached
    CASE i_eventtype.
      WHEN 'IPE'.
        IF i_event EQ 'CLEAR'.
          CLEAR rbt_inv_disc.
          CLEAR rbt_damgd_label.
          CLEAR rbt_damgd_rack.
        ENDIF.

        IF i_event EQ 'SAVE'.
          DATA(lt_values) = VALUE /mobisys/msb_str_value_in_t( FOR ls_values IN values
                                                                ( ls_values ) ).

          IF lo_defect_category IS NOT BOUND.
            lo_defect_category = NEW ymtle10358cl_defect_category( ).
          ENDIF.
          IF lo_defect_dao IS NOT BOUND.
            lo_defect_dao = NEW ymtle10358cl_defect_dao( ).
          ENDIF.

          DATA(ls_def_cat_parameters) = VALUE ymtle10358s_def_cat_param( uname = i_user
                                                                         event = i_event
                                                                         rbt_inv_disc = rbt_inv_disc
                                                                         rbt_damgd_label = rbt_damgd_label
                                                                         rbt_damgd_rack = rbt_damgd_rack ).
          "Create defect and set the bin blocked
          IF lo_defect_category->check_radiobutton( ls_def_cat_parameters ).
            TRY.
                DATA(ls_defect) = lo_defect_category->create_defect( EXPORTING is_parameters  = ls_def_cat_parameters
                                                                               it_values      = lt_values  ).

                lo_defect_category->set_putaway_block_status( EXPORTING is_parameters  = ls_def_cat_parameters
                                                                        it_values      = lt_values ).
              CATCH ycx_agco_globcore_exception INTO DATA(lx_excp).
                e_msgtxt = lx_excp->if_message~get_text( ).
                e_msgtyp = 'E'.
                e_mask = '001'.
                EXIT.
            ENDTRY.
            IF rbt_inv_disc IS NOT INITIAL.
* Send e-mail for Inventory Discrepancies
              TRY.
                  DATA(ls_parameters) = CORRESPONDING ymtle10358s_param( ls_defect MAPPING uname = ernam  ).
                  DATA(lt_recipients) = lo_defect_dao->get_recipients( ls_parameters ).
                  lo_defect_category->email_notification( EXPORTING is_defect     = ls_defect
                                                                      it_recipients = lt_recipients ).
                CATCH ycx_agco_globcore_exception INTO DATA(lx_excp_2).
                  DATA(lv_msg) = lx_excp_2->if_message~get_text( ).
                  MESSAGE w011(ymtle10358) WITH lv_msg INTO e_msgtxt.   "Defect was created, e-mail could not send: &1
                  e_msgtyp = 'W'.
                  e_mask = '001'.
                  EXIT.
              ENDTRY.
            ENDIF.
          ENDIF.
          MESSAGE i012(ymtle10358) INTO e_msgtxt.     "Defect was created
          e_msgtyp = 'S'.
          e_mask = '001'.
          EXIT.
        ENDIF.
    ENDCASE.
  ENDDO.

* <<< End of customer own coding   <<<



**** PAI- generated by MSB 28.11.2022 ***
**** DO NOT CHANGE / CHANGES WILL BE OVERWRITTEN ***
*
  INCLUDE z_msb_ysa_ymtl_def_pai_exit .





ENDFUNCTION.
