FUNCTION Z_MSB_YSA_YMTL_DEF_001_PAI.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_APPL) TYPE  /MOBISYS/MSB_APPL OPTIONAL
*"     VALUE(I_DEVICEID) TYPE  /MOBISYS/MSB_DEVICEID OPTIONAL
*"     VALUE(I_EVENT) TYPE  /MOBISYS/MSB_CEVENT OPTIONAL
*"     VALUE(I_EVENTTYPE) TYPE  /MOBISYS/MSB_CEVENTTYPE OPTIONAL
*"     REFERENCE(I_HELPER) TYPE REF TO  /MOBISYS/CL_MSB_RTS OPTIONAL
*"     VALUE(I_MASK) TYPE  /MOBISYS/MSB_MASKID OPTIONAL
*"     VALUE(I_SESSION) TYPE  /MOBISYS/MSB_SESSION OPTIONAL
*"     VALUE(I_TCODE) TYPE  /MOBISYS/MSB_TCODE OPTIONAL
*"     VALUE(I_USER) TYPE  SYST-UNAME OPTIONAL
*"  EXPORTING
*"     VALUE(E_APPL) TYPE  /MOBISYS/MSB_APPL
*"     VALUE(E_MASK) TYPE  /MOBISYS/MSB_MASKID
*"     VALUE(E_MSGNO) TYPE  MSGNO
*"     VALUE(E_MSGTXT) TYPE  MSGTX
*"     VALUE(E_MSGTYP) TYPE  MSGTY
*"     VALUE(E_TCODE) TYPE  /MOBISYS/MSB_TCODE
*"     VALUE(E_USER) TYPE  /MOBISYS/MSB_UNAME
*"  TABLES
*"      VALUES STRUCTURE  /MOBISYS/MSB_STR_VALUE_IN OPTIONAL
*"  CHANGING
*"     REFERENCE(C_APPDATA) TYPE  /MOBISYS/MSB_APPDATA OPTIONAL
*"--------------------------------------------------------------------
**** PAI- generated by MSB 28.11.2022 ***
**** DO NOT CHANGE / CHANGES WILL BE OVERWRITTEN ***
*
INCLUDE Z_MSB_YSA_YMTL_DEF_PAI_ENTRY .



* DATA EDT_LAGP_LGPLA TYPE LGPLA *.
* DATA EDT_MARA_MATNR TYPE MATNR *.
* DATA EDT_T301_LGTYP TYPE LGTYP *.
* DATA RBT_DAMGD_LABEL TYPE CHAR1 *.
* DATA RBT_DAMGD_RACK TYPE CHAR1 *.
* DATA RBT_INV_DISC TYPE CHAR1 *.


* >>> Begin of customer own coding >>>
*----------------------------------------------------------------------*
* Author: Marton Papp
* Date:   2022.02.22.
* CR/IN: CHG0083294 - HES project
*----------------------------------------------------------------------*
* Short description:
* Non-material defect creation
*----------------------------------------------------------------------*
* Changes
* Index Name         Date        Short description
*----------------------------------------------------------------------*

  DATA: lt_bdcmsgcoll TYPE trty_bdcmsgcoll.
  DATA(ls_parameters) = VALUE ymtle10358s_param( uname = i_user
                                                event = i_event
                                                lgtyp = edt_t301_lgtyp
                                                lgpla = edt_lagp_lgpla
                                                matnr = edt_mara_matnr ).


DO 1 TIMES.         "Generated Exit Include should be reached
  CASE i_eventtype.
    WHEN 'IPE'.
      IF i_event EQ 'CLEAR'.
        CLEAR edt_t301_lgtyp.
        CLEAR edt_lagp_lgpla.
        CLEAR edt_mara_matnr.
      ENDIF.
    WHEN 'NAV'.
      IF i_event EQ 'CONTINUE'.
        TRY.
            DATA(lo_defect_location) = NEW ymtle10358cl_defect_location( ).
            IF lo_defect_location->check_parameters( EXPORTING is_parameters = ls_parameters
                                                     CHANGING  ct_bdcmsgcoll = lt_bdcmsgcoll ).
            ENDIF.
          CATCH ycx_agco_globcore_exception INTO DATA(lr_excp).
            e_msgtxt = lr_excp->if_message~get_text( ).
            e_msgtyp = 'E'.
            e_mask = '001'.
            EXIT.
        ENDTRY.
      ENDIF.
  ENDCASE.
ENDDO.

* <<< End of customer own coding   <<<



**** PAI- generated by MSB 28.11.2022 ***
**** DO NOT CHANGE / CHANGES WILL BE OVERWRITTEN ***
*
INCLUDE Z_MSB_YSA_YMTL_DEF_PAI_EXIT .





ENDFUNCTION.
