**** PAI-ENTRY generated by MSB 28.11.2022 ***
**** DO NOT CHANGE / CHANGES WILL BE OVERWRITTEN ***
*
DATA EDT_LAGP_LGPLA TYPE LGPLA .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'EDT_LAGP_LGPLA'.
EDT_LAGP_LGPLA = VALUES-CVALUE.
*
DATA EDT_MARA_MATNR TYPE MATNR .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'EDT_MARA_MATNR'.
EDT_MARA_MATNR = VALUES-CVALUE.
*
DATA EDT_T301_LGTYP TYPE LGTYP .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'EDT_T301_LGTYP'.
EDT_T301_LGTYP = VALUES-CVALUE.
*
DATA RBT_DAMGD_LABEL TYPE CHAR1 .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'RBT_DAMGD_LABEL'.
RBT_DAMGD_LABEL = VALUES-CVALUE.
*
DATA RBT_DAMGD_RACK TYPE CHAR1 .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'RBT_DAMGD_RACK'.
RBT_DAMGD_RACK = VALUES-CVALUE.
*
DATA RBT_INV_DISC TYPE CHAR1 .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'RBT_INV_DISC'.
RBT_INV_DISC = VALUES-CVALUE.
*
*
e_appl = i_appl.
e_tcode = i_tcode.
e_mask = i_mask.
*
  DATA: vl_tcode2  TYPE /mobisys/msbhist-tcode2,
        vl_maskid2 TYPE /mobisys/msbhist-maskid2,
        vl_appl2   type /mobisys/msbhist-appl2,
        vl_no_transaction_log type c,
        vl_generate_appl type /mobisys/msb_appl,
        vl_1(10) TYPE c,
        vl_2(10) TYPE c,
        vl_3(10) TYPE c.
*
  CASE i_eventtype.
    WHEN 'NAV'.
      case i_event.
        when 'BACK'.
          SELECT SINGLE appl tcode maskid appl2 tcode2 maskid2
            FROM /mobisys/msbhist
            INTO (e_appl, e_tcode, e_mask,
                  vl_appl2, vl_tcode2, vl_maskid2)
            WHERE deviceid = i_deviceid
              AND uname    = i_user.
          IF e_appl = i_appl and e_tcode = i_tcode AND e_mask = i_mask.
            e_appl  = vl_appl2.
            e_tcode = vl_tcode2.
            e_mask  = vl_maskid2.
          ENDIF.
        when 'MAIN'.
          SELECT SINGLE tcode_start
            FROM /mobisys/msbappl
            INTO e_tcode
            WHERE appl = i_appl.
          CLEAR e_mask.
        when 'CONTINUE'.
          SELECT SINGLE maskid_next
            FROM /mobisys/msbmask
            INTO e_mask
            WHERE appl   = i_appl
              AND tcode  = i_tcode
              AND maskid = i_mask.
          IF sy-subrc NE 0 or e_mask is initial.
            e_mask = i_mask.
          ENDIF.
          e_tcode = i_tcode.
        when 'BACK_TRA'.
          SELECT SINGLE appl_prev_tra tcode_prev_tra maskid_prev_tra
            FROM /mobisys/msbhist
            INTO (vl_appl2, vl_tcode2, vl_maskid2)
            WHERE deviceid = i_deviceid
              AND uname    = i_user.
          IF sy-subrc = 0 AND NOT vl_appl2 IS INITIAL.
            e_appl  = vl_appl2.
            e_tcode = vl_tcode2.
            e_mask  = vl_maskid2.
          ENDIF.
        when 'BACK_APPL'.
          SELECT SINGLE appl_prev_app tcode_prev_app maskid_prev_app
            FROM /mobisys/msbhist
            INTO (vl_appl2, vl_tcode2, vl_maskid2)
            WHERE deviceid = i_deviceid
              AND uname    = i_user.
          IF sy-subrc = 0 AND NOT vl_appl2 IS INITIAL.
            e_appl  = vl_appl2.
            e_tcode = vl_tcode2.
            e_mask  = vl_maskid2.
          ENDIF.
        when others.
      endcase.
    WHEN 'TRA'.
      SPLIT i_event AT '/' INTO vl_1 vl_2.
      IF vl_2 IS INITIAL.
        e_tcode = vl_1.
      ELSE.
        e_appl  = vl_1.
        e_tcode = vl_2.
      ENDIF.
      SELECT SINGLE APPL
        FROM /mobisys/msbmask
        INTO vl_generate_appl
        WHERE appl  = e_appl
          AND tcode = e_tcode.
      IF sy-subrc NE 0.
        e_appl  = i_appl.
        e_tcode = i_tcode.
      ELSE.
        CLEAR e_mask.
      ENDIF.
    WHEN 'MSK'.
      SPLIT i_event AT '/' INTO vl_1 vl_2 vl_3.
      IF vl_3 IS INITIAL.
        IF vl_2 IS INITIAL.
          e_mask  = vl_1.
        ELSE.
          e_mask  = vl_2.
          e_tcode = vl_1.
        ENDIF.
      ELSE.
        e_mask  = vl_3.
        e_tcode = vl_2.
        e_appl  = vl_1.
      ENDIF.
      SELECT SINGLE tcode
        FROM /mobisys/msbmask
        INTO e_tcode
       WHERE appl   = e_appl
         AND tcode  = e_tcode
         AND maskid = e_mask.
      IF sy-subrc NE 0.
        e_appl  = i_appl.
        e_tcode = i_tcode.
        e_mask  = i_mask.
      ENDIF.
    WHEN OTHERS.
  ENDCASE.
  DATA: vl_dif TYPE f.
  DATA: vl_timschar(6) TYPE c.
