**** PBO-ENTRY generated by MSB 28.11.2022 ***
**** DO NOT CHANGE / CHANGES WILL BE OVERWRITTEN ***
*
DATA EDT_LAGP_LGPLA TYPE LGPLA .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'EDT_LAGP_LGPLA'.
EDT_LAGP_LGPLA = VALUES-CVALUE.
*
DATA EDT_MARA_MATNR TYPE MATNR .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'EDT_MARA_MATNR'.
EDT_MARA_MATNR = VALUES-CVALUE.
*
DATA EDT_T301_LGTYP TYPE LGTYP .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'EDT_T301_LGTYP'.
EDT_T301_LGTYP = VALUES-CVALUE.
*
DATA RBT_DAMGD_LABEL TYPE CHAR1 .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'RBT_DAMGD_LABEL'.
RBT_DAMGD_LABEL = VALUES-CVALUE.
*
DATA RBT_DAMGD_RACK TYPE CHAR1 .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'RBT_DAMGD_RACK'.
RBT_DAMGD_RACK = VALUES-CVALUE.
*
DATA RBT_INV_DISC TYPE CHAR1 .
CLEAR VALUES .
READ TABLE VALUES WITH KEY COMPID = 'RBT_INV_DISC'.
RBT_INV_DISC = VALUES-CVALUE.
*
DATA: vl_globaldata TYPE /mobisys/msb_globaldata.
DATA: sl_values TYPE /mobisys/msb_str_value_in.
DATA: sl_glda TYPE /mobisys/msbglda.
DATA: vl_tabix LIKE sy-tabix.
DATA: vl_cdatatype type /mobisys/msbcomp-cdatatype.
DATA: sl_comp_pbo_xx type /mobisys/msbcomp.
FIELD-SYMBOLS: <fs> TYPE ANY.
  LOOP AT values INTO sl_values.
    vl_tabix = sy-tabix.
    SELECT mandt appl tcode maskid compid globaldata cdatatype
      FROM /mobisys/msbcomp
      UP TO 1 ROWS
      INTO CORRESPONDING FIELDS OF sl_comp_pbo_xx
      WHERE appl   = i_appl
        AND tcode  = i_tcode
        AND compid = sl_values-compid
        AND globaldata = 'X'
        AND active = 'X'
      ORDER BY PRIMARY KEY.
    ENDSELECT.
    IF sy-subrc = 0.
      SELECT SINGLE *
        FROM /mobisys/msbglda
        INTO sl_glda
        WHERE deviceid  = i_deviceid
         and uname      = i_user
         and compid     = sl_values-compid
         AND sessionid  = i_session.
      IF sy-subrc = 0.
        sl_values-cvalue = sl_glda-value.
        IF sl_comp_pbo_xx-cdatatype = 'QUAN'.
          TRANSLATE sl_glda-value USING ',.'.
        ENDIF.
        MODIFY values FROM sl_values INDEX vl_tabix.
        ASSIGN (sl_values-compid) TO <fs>.
          IF sy-subrc = 0.
            <fs> = sl_glda-value.
            UNASSIGN <fs>.
          ENDIF.
      ENDIF.
    ENDIF.
  ENDLOOP.
  DATA: vl_dif TYPE f.
  DATA: vl_timschar(6) TYPE c.
